
default: &default
  adapter: postgresql
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: daily_development
  pool: 5
  username: daily
  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: daily_test
  pool: 5
  username: daily
  password: password1
